name: Chewy2.0Builds_Proxy_Server
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PW:  ${{ secrets.DOCKER_PW }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PW
      - name: docker build chris-proxy-server
        run: docker build -f Dockerfile -t feckwame/chris-proxy-server .
      - name: docker push
        run: |
          docker push feckwame/chris-proxy-server
